### ISSUE TITLE
implement abstract automatic training manager

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-behavior-curriculum#13]
no database stuff, use pd.DataFrame as your interaction layer.

**Comment by hanhou** [comment]
Example: https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training/blob/ef3ee668ad0532d509a7e61160d68df7b68c15a5/code/aind_auto_train/auto_train_manager.py#L27

**Comment by dyf** [comment]
@jwong-nd, notes from 3/26:
- update to ensure that multiple policies can be active at once
- @bruno-f-cruz said something about `tuple[Policy,Stage]` "is for analysis" that I didn't understand
- need to more extensive test cases (backwards transitions, manual transitions)
- do we need policy constraints? need to discuss.

**Comment by bruno-f-cruz** [comment]
Basically make sure that the history output structure is formalized somewhere instead of a generic Tuple object. I suspect that people might want to use this for analysis.

**Comment by jwong-nd** [comment]
Recently updated with multiple active policies, see [bae0d32](https://github.com/AllenNeuralDynamics/aind-behavior-curriculum/pull/11/commits/bae0d322b8f85ad0d5b5fb35c65f2c58f790342d)

**Comment by jwong-nd** [comment]
Adding final tests in branch 'trainer-tests'

**Comment by jwong-nd** [comment]
Testing complete

**Comment by bruno-f-cruz** [comment]
This is done, closing.
