### ISSUE TITLE
Add curriculum visualization

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-behavior-curriculum#17]

**Comment by bruno-f-cruz** [comment]
lib choices to consider:

-graphx
-graphviz
-pyviz

**Comment by jwong-nd** [comment]
See commit https://github.com/AllenNeuralDynamics/aind-behavior-curriculum/pull/11/commits/bb3b05a3b541c2894fe45881372e2dc3ae4870c3

**Comment by bruno-f-cruz** [comment]
Do you have a solution for the Windows deployment that is supported by pip? I am still a bit reticent about using graphviz for this reason...

**Comment by jwong-nd** [comment]
not the cleanest, but we can consider a post-install script. I found networkx and pyviz to be lacking some features like directed, labelled edges which are difficult if not impossible to generate reliably so I picked graphviz

**Comment by bruno-f-cruz** [comment]
Happy to go with a post-install script. Lets talk during the meeting!

**Comment by bruno-f-cruz** [comment]
We agreed that graph assets would be pre-generated and the rig would not need to depend on graphviz. As a result, this should no longer be a concert.
