### ISSUE TITLE
Refactor graph data model

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-behavior-curriculum#18]

**Comment by jwong-nd** [comment]
Basic refactor in https://github.com/AllenNeuralDynamics/aind-behavior-curriculum/pull/11/commits/bb3b05a3b541c2894fe45881372e2dc3ae4870c3

Need Generics for correct Deserialization

**Comment by bruno-f-cruz** [comment]
Done, tested and released. Closing.
