### ISSUE TITLE
Implement Task schema

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-behavior-curriculum#2]
- [ ] add a basic Task schema, based on various examples
- [ ] add an example Task in `./examples/`
- [ ] add a unit test that constructs the example Task

@bruno-f-cruz @hanhou please add links to your repos here.

**Comment by bruno-f-cruz** [comment]
- [aind-foraging-behavior-bonsai-automatic-training](https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training/tree/main/code/aind_auto_train/schema)

- [Aind.Behavior.MouseUniversity](https://github.com/AllenNeuralDynamics/Aind.Behavior.MouseUniversity/blob/main/src/aind_behavior_mouse_university/base/__init__.py)


Also, I was looking into how recursive models work in pydantic and we might want to find a better way to pass the references around if needed.

**Comment by alexpiet** [comment]
This repo is a central organizing point for behavior things: https://github.com/AllenNeuralDynamics/aind-behavior-blog

[dynamic foraging task](https://github.com/AllenNeuralDynamics/dynamic-foraging-task)

**Comment by jwong-nd** [comment]
@alexpiet it appears like I cannot access the aind-behavior-blog link, 404 error

**Comment by bruno-f-cruz** [comment]
You (along with all the scientific computing team) should now have access.
