### ISSUE TITLE
Improve docs cross-referencing

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-behavior-curriculum#24]
We should consider refactoring the docs website to cross-reference with the API documentation of the package. For instance, `Metrics` should link to the respective technical reference instead of just highlighting the word.
Additionally, we should consider splitting the technical documentation by module instead of flattening the whole thing. As an example:

```
The callables in **Policy** and ...
```
should be replaced by:

```
The callables in :py:class:`~aind_behavior_curriculum.curriculum.Policy` and...
```

**Comment by jwong-nd** [comment]
Agree with this, can lump into the next PR
