### ISSUE TITLE
Implement Curriculum schema

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-behavior-curriculum#5]
- [ ] Add the generic Curriculum schema
- [ ] Add an example that uses the basic Task from #2

**Comment by bruno-f-cruz** [comment]
Both links provided in #2 also contain examples that may be informative.

**Comment by hanhou** [comment]
Example from Han
- [Curriculum schema](https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training/blob/main/code/aind_auto_train/schema/curriculum.py)
- [Example curriculum](https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training/blob/main/code/aind_auto_train/curriculums/uncoupled_no_baiting_0p1.py)
- [Unit test: serialization and deserialization](https://github.com/AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training/blob/main/code/aind_auto_train/demo_schema.ipynb)

**Comment by bruno-f-cruz** [comment]
Closing this. We should replace it with a workshop-like session at some point.
